method: anchorrec
resume: False
finetune: True
weight: ['ckpts/only_detection.pth','ckpts/detection_refine.pth']
seed: 10
use_rgb: True
device:
  use_gpu: True
  gpu_ids: '2'
  num_workers: 1
data:
  split: quad_joint
  mincount: 40
  maxcount: 250 #500
  min_pts2d_range: 20
  min_pts2d_number: 20
  positive_iou_thresh: 0.1
  min_objectness: 0.05

  num_point: 80000
  num_target: 256
  num_quad_proposal: 256
  no_height: False
  use_rgb: True
  vote_factor: 1
  cluster_sampling: vote_fps
  ap_iou_thresh: 0.25
  use_color_detection: False
  use_color_completion: False
  world_scale_range: [ .9, 1.1 ]
  noise_traslation_std: 0.1
model:
  backbone:
    method: Pointnet2Backbone
  detection:
    method: ProposalModule
    num_proposal: 256
    cluster_sampling: vote_fps
    num_sample: 16
    shape:
      residual: true
      scale: 1.0
      subnetworks: 1
      supervise: True #False #true
      use_gt_anchors: true
      wd0: 1.0
      wd1: 1.0
      wd2: 1.0
  quad_detection:
    iou_threshold: 0.05
    loss: QuadDetectionLoss
    method: QuadProposalModule
    num_sample: 32
    sa: true # False #true
    shape:
      subnetworks: 3
      scale: 1.0
      residual: True
      supervise: True #False #True
      wd0: 1.0
      wd1: 1.0
      wd2: 1.0
  detection_head:
    method: FusionPredictHead_no_rgb
    rgb_input_channels: 128
    proposal_feat_channels: 128
    hidden_dim: 128
    use_anchor: True
  GenerateInstanceFeat:
    method: InstanceFeatSampling
    sample_radius: 0.1
    nsample: [ 30,5 ]
    min_num_pts: 20
    rescale_range: [ 0.7, 1.3 ]
    shift_range: [ -10,10 ]
    image_size: 256 #400
    min_pts2d_range: 20
  img_encoder:
    method: ResNet_fpn
    frozen_stages: 2
    use_point_mask: False
    out_channels: 256
  detection_refine_head:
    method: FusionPredictHead
    rgb_input_channels: 256
    hidden_dim: 128
test:
  phase: 'detection_with_rgb'
  test_phase: 'detection'
  test_quad: False
  batch_size: 1
  use_cls_nms: True
  use_3d_nms: True
  ap_iou_thresholds: [0.5,0.25]
  remove_under_floor: False
  faster_eval: True
  nms_iou: 0.25
  use_old_type_nms: False
  per_class_proposal: True
  conf_thresh: 0.05
  quad_conf_thresh: 0.05
log:
  vis_path: visualization
  save_results: False
  vis_step_val: 30
  vis_step_train: 150
  vis_step_epoch: 50
  print_step: 10
  path: out/detection_with_rgb
