method: anchorrec
finetune: False #True # False for training, True for testing or finetuning
resume: False
weight: 'out/only_detection/model_detection.pth'
seed: 10
multiple_gpus: False
use_rgb: False
device:
  use_gpu: True
  gpu_ids: '1'
  num_workers: 2
data:
  dataset: scannet
  split:  quad_joint
  num_point: 80000
  num_target: 256
  num_quad_proposal: 256
  vote_factor: 1
  cluster_sampling: vote_fps
  ap_iou_thresh: 0.25
  no_height: False
  use_color_detection: False
  use_color_completion: False
  world_scale_range: [ .9, 1.1 ]
  noise_traslation_std: 0.1
model:
  backbone:
    method: Pointnet2Backbone
  detection:
    method: ProposalModule
    num_proposal: 256
    cluster_sampling: vote_fps
    num_sample: 16
    shape:
      residual: true
      scale: 1.0
      subnetworks: 1
      supervise: True
      use_gt_anchors: False
      wd0: 1.0
      wd1: 1.0
      wd2: 1.0
  detection_head:
    method: FusionPredictHead_no_rgb
    proposal_feat_channels: 128
    hidden_dim: 128
    use_anchor: True
    loss: DetectionLoss
  quad_detection:
    iou_threshold: 0.05
    loss: QuadDetectionLoss
    method: QuadProposalModule
    num_sample: 32
    sa: true # use self=attention layers
    shape:
      subnetworks: 3
      scale: 1.0
      residual: True
      supervise: True #False #True
      wd0: 1.0
      wd1: 1.0
      wd2: 1.0
optimizer:
  method: Adam
  lr: 1e-3
  betas: [0.9, 0.999]
  eps: 1e-08
  weight_decay: 0.0001
  grad_norm_clip: 10
scheduler:
  method: ReduceLROnPlateau
  patience: 20
  factor: 0.5
  threshold: 0.01
bnscheduler:
  bn_decay_step: 20
  bn_decay_rate: 0.5
  bn_momentum_init: 0.5
  bn_momentum_max: 0.001
train:
  epochs: 240
  eval_map_start_epoch: 180
  phase: 'joint_detection' #switch to 'joint_detection' to train object detection and quad detection together
  freeze: []
  batch_size: 8
val:
  phase:  'joint_detection' #switch to 'joint_detection' to validate object detection and quad detection together
  save_best_according_to: 'detection'
  save_quad_ckpt_thresh: 0.7 #save checkpoint when f1>thresh
  batch_size: 1
  use_cls_nms: True
  use_3d_nms: True
  ap_iou_thresholds: [0.5]
  remove_under_floor: True
  faster_eval: True
  nms_iou: 0.25
  use_old_type_nms: False
  per_class_proposal: True
  conf_thresh: 0.05
  quad_conf_thresh: 0.05
test:
  batch_size: 1
  phase: detection' #switch to 'joint_detection' to test object detection and quad detection together
  test_phase: 'detection'
  use_cls_nms: True
  use_3d_nms: True
  ap_iou_thresholds: [ 0.5, 0.25 ]
  remove_under_floor: True
  faster_eval: True
  nms_iou: 0.25
  use_old_type_nms: False
  per_class_proposal: True
  conf_thresh: 0.05
  quad_conf_thresh: 0.05
log:
  vis_path: visualization
  save_epoch_step: 5
  save_results: False
  vis_step: 1
  print_step: 20
  path: out/joint_detection
  quad_dump_threshold: 0.5
  dump_threshold: 0.5
