method: anchorrec_detection_refine
resume: False
finetune: True
weight: 'out/rgb_pretrain/model_last.pth'
seed: 10
multiple_gpus: False
use_rgb: True
device:
  use_gpu: True
  gpu_ids: '0'
  num_workers: 1
data:
  dataset: SingleObject #scannet
  num_target: 64
  input_path: 'out/prepare_data_for_refine/original'
  min_pts2d_range: 20
  min_pts2d_number: 20
  positive_iou_thresh: 0.1
  min_objectness: 0.05
  # for reconstruction
  pretrained_features_pth: 'datasets/latentz.pkl'
  shapenet_path: /home/dmy/data/datasetds/ShapeNetv2_data
  image_size: 256
  output_gt_z_mesh: True
  use_rgb: True
  point_recall_thresh: 0.2
  point_precision_thresh: 0.2
  num_proposal: 64 #256 #64
model:
  img_encoder:
    method: ResNet_fpn
    frozen_stages: 2
    use_point_mask: False
    out_channels: 256
    optimizer:
      method: Adam
      lr: 1e-4
      betas: [ 0.5, 0.999 ]
      eps: 1e-08
      weight_decay: 0.0005
      grad_norm_clip: 10
  detection_refine_head:
    method: FusionPredictHead
    rgb_input_channels: 256
    hidden_dim: 128
optimizer:
  method: Adam
  lr: 1e-4
  betas: [0.5, 0.999]
  eps: 1e-08
  weight_decay: 0.0005
  grad_norm_clip: 10
scheduler:
  method: ExponentialLR
train:
  epochs: 15
#  freeze: []
  freeze: ['img_encoder']
  batch_size: 128
  eval_map_start_epoch: 0
val:
  batch_size: 1
  phase: detection
  use_cls_nms: True
  use_3d_nms: True
  ap_iou_thresholds: [ 0.5,0.25 ]
  faster_eval: True #False: not removing empty bbox
  nms_iou: 0.25
  use_old_type_nms: False
  per_class_proposal: True
  conf_thresh: 0.05
  quad_conf_thresh: 0.05
  remove_under_floor: True
  evaluate_mesh_mAP: True
test:
  batch_size: 1
log:
  vis_path: visualization
  save_results: False
  vis_step_val: 30
  vis_step_train: 150
  vis_step_epoch: 50
  print_step: 10
  path: out/refine 
